### PR TITLE
Updated to the latest commits to support image list for v4 cameras.

### PR DESCRIPTION
**Pull request by aroller**
**Description**
Image list is not working with v4 of the H20.  This OSDK will fix that, among other things.

**For Developers**
Make sure that you have done all of the steps necessary to merge a PR:
- [ ] My code follows the coding style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated and created tests accordingly.
- [ ] My PR is linked to an issue.
- [ ] The PR fully addresses the issue, or follow up issues are created.

**For Reviewers**
- [ ] Are the tests that need to be updated changed?
- [ ] Does the code conform to the standards of the project?
- [ ] Is the design consistent with the architecture of the project?

**Additional context**
Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by aroller** [comment]
@ahmed-elsaharti I think this will should be merged into main today.  Speak up if that is a problem.

**Comment by ramtinka** [comment]
tested in the field and worked fine in flight manual

**Comment by aroller** [comment]
image

@ramtinka we need to merge this into main, not just close it.

**Review by ramtinka — APPROVED** [review]
We tested in the field and it was working more information [here](https://airtonomy.slack.com/archives/C03GMRSCX7Y/p1666200261614069)

**Pull request merged**
